**Business Understanding of MPG Dataset**

The MPG dataset contains automobile specifications and fuel efficiency information of different vehicles.

 The main goal of this project is to predict the MPG (miles per gallon) of a vehicles using its technical features.

In [1]:
!pip install tensorflow
!pip install pymysql
!pip install sqlalchemy

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.20.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.1)
Requirement already satisfied: protobuf>=5.28.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.80.0)
Requirement already satisfied: tensorboard~=2.20.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.16.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.19.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.4.22)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.10.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (11.3.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.1.8)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.2)
Requirement already satisfied: pymysql in /usr/local/lib/python3.12/dist-packages (1.1.3)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error,r2_score

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

from sqlalchemy import create_engine
import pymysql

**Loading Dataset**

In [3]:
df = sns.load_dataset('mpg')
print(df.head(3))

    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0
1  15.0          8         350.0       165.0    3693          11.5
2  18.0          8         318.0       150.0    3436          11.0

   model_year origin                       name
0          70    usa  chevrolet chevelle malibu
1          70    usa          buick skylark 320
2          70    usa         plymouth satellite

In [4]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
 8   name          398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB
None

**Missing values**

In [5]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

In [6]:
df[df['horsepower'].isnull()]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
32,25.0,4,98.0,NaN,2046,19.0,71,usa,ford pinto
126,21.0,6,200.0,NaN,2875,17.0,74,usa,ford maverick
330,40.9,4,85.0,NaN,1835,17.3,80,europe,renault lecar deluxe
336,23.6,4,140.0,NaN,2905,14.3,80,usa,ford mustang cobra
354,34.5,4,100.0,NaN,2320,15.8,81,europe,renault 18i
374,23.0,4,151.0,NaN,3035,20.5,82,usa,amc concord dl

**check the number of records**

In [7]:
df.shape

(398, 9)

**drop the missing rows**

In [8]:
df = df.dropna()
df.shape

(392, 9)

In [9]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

**Remove Categorical Columns**

In [10]:
df=df.drop(['origin','name','model_year'],axis=1)
df.head(3)

    mpg  cylinders  displacement  horsepower  weight  acceleration
0  18.0          8         307.0       130.0    3504          12.0
1  15.0          8         350.0       165.0    3693          11.5
2  18.0          8         318.0       150.0    3436          11.0

**Insights**

Categorical columns were removed because neural networks require nmerical input.

This preprocessing step prepares the dataset for deep learning.

**Defining Features and Target Variable**

In [11]:
X = df.drop('mpg',axis=1)
y = df['mpg']

print(X.head(3))
print(y.head(3))

   cylinders  displacement  horsepower  weight  acceleration
0          8         307.0       130.0    3504          12.0
1          8         350.0       165.0    3693          11.5
2          8         318.0       150.0    3436          11.0
0    18.0
1    15.0
2    18.0
Name: mpg, dtype: float64

**Train Test Split**

In [12]:
X_train, X_test,y_train,y_test =train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
    )

**Feature Scaling using Standard Scaler**

In [13]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

**Building Multi Layer Perceptron Feed Forward Neural Network Model**

In [14]:
model =tf.keras.models.Sequential([
    tf.keras.layers.Dense(64, activation='relu',input_shape = (X_train_scaled.shape[1],)),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(16,activation='relu'),
    tf.keras.layers.Dense(1)
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

**Compiling the Neural Network**

In [15]:
model.compile(optimizer='adam',
              loss='mean_squared_error',
              metrics=['mae']
)

**Model Summary**

In [16]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           384 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,009 (11.75 KB)

 Trainable params: 3,009 (11.75 KB)

 Non-trainable params: 0 (0.00 B)

**Insights**

The neural network contains multiple hidden layers.
Each layer learns complex relationships bvetween vehicle specifications and MPG values.
The model architecture helps improve prediction capability.

**Training the Neural Network**

In [17]:
history = model.fit(X_train_scaled,
                    y_train,
                    epochs =100,
                    batch_size=16,
                    verbose =1
)

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 598.4247 - mae: 23.1365
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 541.8391 - mae: 21.9351
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 421.0513 - mae: 19.0323
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 211.1385 - mae: 12.8281
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 66.2084 - mae: 6.7479
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 50.7480 - mae: 5.5490
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 40.9694 - mae: 4.9799
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 35.3908 - mae: 4.6414
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 30.9913 - mae: 4.3034
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 27.4204 - mae: 4.0095
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 24.8633 - mae: 3.7841
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 22.9560 - mae: 3.5896
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 21.7296 - mae: 3.4774
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 20.4959 - mae: 3.3496
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 19.7121 - mae: 3.2706
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 19.3709 - mae: 3.2371
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 18.7679 - mae: 3.2039
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 17.8549 - mae: 3.0818
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 17.5826 - mae: 3.0833
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 17.2336 - mae: 3.0385
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 16.5875 - mae: 2.9714
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 16.3596 - mae: 2.9583
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 16.0330 - mae: 2.9254
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 16.0410 - mae: 2.9359
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 15.6370 - mae: 2.8758
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 15.5465 - mae: 2.9114
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 15.3643 - mae: 2.8819
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 15.2377 - mae: 2.8476
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 14.9376 - mae: 2.8493
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 14.9132 - mae: 2.8276
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 14.9946 - mae: 2.8310
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 14.4871 - mae: 2.7986
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 14.5814 - mae: 2.8090
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 14.3347 - mae: 2.7849
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.3892 - mae: 2.7596
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.1099 - mae: 2.7823
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.0709 - mae: 2.7604
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.2577 - mae: 2.7860
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.0342 - mae: 2.7514
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.9433 - mae: 2.7579
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.9810 - mae: 2.7474
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.8057 - mae: 2.7186
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.0050 - mae: 2.7767
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.9024 - mae: 2.7354
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.2666 - mae: 2.7762
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.4042 - mae: 2.7882
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.6193 - mae: 2.7329
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.5428 - mae: 2.7137
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.3882 - mae: 2.7012
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.6523 - mae: 2.7216
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.4859 - mae: 2.7197
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.3974 - mae: 2.6724
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.3592 - mae: 2.7017
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.5453 - mae: 2.7258
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.3153 - mae: 2.6841
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.2634 - mae: 2.7024
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 13.4198 - mae: 2.6605
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.1857 - mae: 2.7002
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.3588 - mae: 2.6560
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.3658 - mae: 2.6852
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.6989 - mae: 2.7496
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.2981 - mae: 2.6787
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.3645 - mae: 2.6709
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.1315 - mae: 2.6552
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.0477 - mae: 2.6364
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.0552 - mae: 2.6854
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.0549 - mae: 2.6547
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 13.0325 - mae: 2.6760
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.6614 - mae: 2.7139
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.9906 - mae: 2.6433
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.2954 - mae: 2.6896
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.5800 - mae: 2.7395
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.9042 - mae: 2.6579
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.9863 - mae: 2.6627
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 13.1302 - mae: 2.7202
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.8438 - mae: 2.6246
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.0367 - mae: 2.6626
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 13.1483 - mae: 2.6836
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 12.6674 - mae: 2.6268
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.7896 - mae: 2.5928
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 13.0454 - mae: 2.6401
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.5880 - mae: 2.6105
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.7738 - mae: 2.6157
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.7410 - mae: 2.6162
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.6768 - mae: 2.6149
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 13.1512 - mae: 2.6441
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.9232 - mae: 2.6676
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.6999 - mae: 2.6061
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.5759 - mae: 2.5910
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.4313 - mae: 2.5849
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.6266 - mae: 2.6121
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.5880 - mae: 2.6055
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.8527 - mae: 2.6019
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.8671 - mae: 2.5970
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.8770 - mae: 2.6418
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.4937 - mae: 2.5729
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.4547 - mae: 2.5703
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 12.7768 - mae: 2.6052
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.8441 - mae: 2.5987
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 12.2866 - mae: 2.5449

**Insights**

During training,the neural network gradually minimizes prediction error.
As epochs increases,the model learns patterns from the dataset.
Lower validation loss indicates better learning performance.

**Model Evaluation**

In [18]:
loss,mae = model.evaluate(X_test_scaled,y_test)

print('Mean Absolute Error:',mae)
print('Loss:',loss)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 15.4049 - mae: 2.8620
Mean Absolute Error: 2.862001895904541
Loss: 15.40488052368164

**Insights**

Lower loss and MAE values indicate better prediction performance.
The model evaluation helps measure how accurately the neural network predicts MPG values.

**Pedicting MPG Values**

In [19]:
y_pred = model.predict(X_test_scaled)

print(y_pred[:10])

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
[[31.042265]
 [19.78188 ]
 [33.682858]
 [29.099628]
 [25.748686]
 [29.985682]
 [12.84803 ]
 [29.529339]
 [20.521896]
 [36.589245]]

**Calculating the R2 Score**

In [20]:
r2 = r2_score(y_test,y_pred)

print('R2 Score:',r2)

R2 Score: 0.698183664539626

**Insights**

Here R2 Score = 0.70,
then the model explains 70% variation in MPG values.
Based on R2 Score,this is a good prediction model.

**Calculating MSE and RMSE**

---

In [21]:
mse = mean_squared_error(y_test,y_pred)
print('MSE:',mse)

rmse = np.sqrt(mse)
print('RMSE:',rmse)

MSE: 15.404881793216363
RMSE: 3.924905322834726

**Insights**

Here MSE is 15.40 ,that means predicted MPG values are closer to actual values.

RMSE is 3.92, that means better prediction accuracy.
RMSE is easier to interpret because it uses the same unit as the target variable.

**Creating Prediction DataFrame**

In [22]:
results = pd.DataFrame({
    'Actual_MPG':y_test,
    'Predicted_MPG':y_pred.flatten()
})
print(results.head(10))

     Actual_MPG  Predicted_MPG
79         26.0      31.042265
276        21.6      19.781879
248        36.1      33.682858
56         26.0      29.099628
393        27.0      25.748686
205        28.0      29.985682
43         13.0      12.848030
235        26.0      29.529339
152        19.0      20.521896
117        29.0      36.589245

**Saving prediction Output**

In [23]:
from google.colab import files

results.to_csv('mpg_predictions.csv',index=False)

files.download('mpg_predictions.csv')